//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desafio_backend.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("desafio_backend.Exception.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo de conta está inválido..
        /// </summary>
        public static string ACCOUNT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma conta cadastrada com esse Email..
        /// </summary>
        public static string ALREADY_EXISTS_EMAIL {
            get {
                return ResourceManager.GetString("ALREADY_EXISTS_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CNPJ é inválido..
        /// </summary>
        public static string CNPJ_INVALID {
            get {
                return ResourceManager.GetString("CNPJ_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF é inválido..
        /// </summary>
        public static string CPF_INVALID {
            get {
                return ResourceManager.GetString("CPF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF/CNPJ é obrigatório..
        /// </summary>
        public static string CPF_REQUIRED {
            get {
                return ResourceManager.GetString("CPF_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do email não é válido..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email é obrigatório..
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saldo insuficiente, a tranferência não foi concluída..
        /// </summary>
        public static string INSUFFICIENT_BALANCE {
            get {
                return ResourceManager.GetString("INSUFFICIENT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saldo insuficiente..
        /// </summary>
        public static string INSUFFICIENT_FUNDS {
            get {
                return ResourceManager.GetString("INSUFFICIENT_FUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é obrigatório..
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A transferência não foi autorizada, tente novamente mais tarde..
        /// </summary>
        public static string NOT_AUTHORIZED_TRANSFER {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZED_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas não conhecidem, tente novamente..
        /// </summary>
        public static string PASSWORD_NOT_EQUALS {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O identificador do Beneficiário é obrigatório..
        /// </summary>
        public static string PAYEE_ID_REQUIRED {
            get {
                return ResourceManager.GetString("PAYEE_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagador desconhecido..
        /// </summary>
        public static string PAYER_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAYER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O pagamento não é válido..
        /// </summary>
        public static string PAYMENT_TYPE_NOT_VALID {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter tamanho máximo de 16 caracteres..
        /// </summary>
        public static string PWD_EXCEED_MAX {
            get {
                return ResourceManager.GetString("PWD_EXCEED_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter tamanho mínimo de 8 caracteres..
        /// </summary>
        public static string PWD_MINIMUN_LENGTH {
            get {
                return ResourceManager.GetString("PWD_MINIMUN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não contém ao menos um caractér especial..
        /// </summary>
        public static string PWD_NOT_CONTAIN_LEAST {
            get {
                return ResourceManager.GetString("PWD_NOT_CONTAIN_LEAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não contém ao menos uma letra minúscula..
        /// </summary>
        public static string PWD_NOT_CONTAIN_LOW_LETTER {
            get {
                return ResourceManager.GetString("PWD_NOT_CONTAIN_LOW_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não contém ao menos um número..
        /// </summary>
        public static string PWD_NOT_CONTAIN_NUMBER {
            get {
                return ResourceManager.GetString("PWD_NOT_CONTAIN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não contém ao menos uma letra maíuscula..
        /// </summary>
        public static string PWD_NOT_CONTAIN_UP_LETTER {
            get {
                return ResourceManager.GetString("PWD_NOT_CONTAIN_UP_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha é obrigatória..
        /// </summary>
        public static string PWD_REQUIRED {
            get {
                return ResourceManager.GetString("PWD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor da transferência é obrigatório..
        /// </summary>
        public static string TRANSFERR_VALUE {
            get {
                return ResourceManager.GetString("TRANSFERR_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não é autorizado para realizar transferência..
        /// </summary>
        public static string UNAUTHORIZED_TO_TRANSFER {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_TO_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nossos serviços estão temporarimente indisponíveis, tente novamente mais tarde..
        /// </summary>
        public static string UNAVAILABLE_SERVICE_NOTIFY {
            get {
                return ResourceManager.GetString("UNAVAILABLE_SERVICE_NOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Destinatário desconhecido..
        /// </summary>
        public static string UNKNOWN_RECIPIENT {
            get {
                return ResourceManager.GetString("UNKNOWN_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CNPJ já está em uso..
        /// </summary>
        public static string USER_CNPJ_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_CNPJ_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF já está em uso..
        /// </summary>
        public static string USER_CPF_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_CPF_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais inválidas..
        /// </summary>
        public static string USER_LOGIN_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_LOGIN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor de transferência precisa ser maior que zero..
        /// </summary>
        public static string VALUE_GREATHER_THAN_ZERO {
            get {
                return ResourceManager.GetString("VALUE_GREATHER_THAN_ZERO", resourceCulture);
            }
        }
    }
}
